//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snork.AspNetSysInfo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snork.AspNetSysInfo.Properties.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v2.2.4 | (c) jQuery Foundation | jquery.org/license */
        ///!function(a,b){&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return b(a)}:b(a)}(&quot;undefined&quot;!=typeof window?window:this,function(a,b){var c=[],d=a.document,e=c.slice,f=c.concat,g=c.push,h=c.indexOf,i={},j=i.toString,k=i.hasOwnProperty,l={},m=&quot;2.2.4&quot;,n=function(a,b){return new n.fn.init(a,b)},o=/^[\s\uFEFF\xA0]+|[\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_2_2_4_min {
            get {
                return ResourceManager.GetString("jquery_2_2_4_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /** 
        /// * Kendo UI v2018.1.117 (http://www.telerik.com/kendo-ui)                                                                                                                                               
        /// * Copyright 2018 Telerik AD. All rights reserved.                                                                                                                                                      
        /// *                                                                                                        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string kendo_all_min {
            get {
                return ResourceManager.GetString("kendo_all_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /** 
        /// * Kendo UI v2018.1.117 (http://www.telerik.com/kendo-ui)                                                                                                                                               
        /// * Copyright 2018 Telerik AD. All rights reserved.                                                                                                                                                      
        /// *                                                                                                        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string kendo_common_min {
            get {
                return ResourceManager.GetString("kendo_common_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $(document).ready(function () {
        ///    $(&apos;#tabstrip&apos;).kendoTabStrip({
        ///        animation: {
        ///            open:
        ///            {
        ///                effects: &apos;fadeIn&apos;
        ///            }
        ///        }
        ///    });
        ///});.
        /// </summary>
        internal static string sysinfojs {
            get {
                return ResourceManager.GetString("sysinfojs", resourceCulture);
            }
        }
    }
}
