//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snork.AspNet.Dashboard.SysInfo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snork.AspNet.Dashboard.SysInfo.Properties.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*a:link {
        ///    background-color: #ffffff;
        ///    color: #000099;
        ///    text-decoration: none;
        ///}
        ///
        ///a:hover { text-decoration: underline; }*/
        ///
        ///body {
        ///    font-family: Sans-Serif
        ///}
        ///
        ////*table {
        ///    border: 0;
        ///    border-collapse: collapse;
        ///    margin-left: auto;
        ///    margin-right: auto;
        ///    text-align: left;
        ///}
        ///
        ///td, th {
        ///    border: 1px solid #000000;
        ///    font-size: 75%;
        ///    vertical-align: baseline;
        ///}
        ///
        ///.title { font-size: 150%; }
        ///
        ///.section { text-align: center; }
        ///
        ///.header {
        ///    background [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string default_css {
            get {
                return ResourceManager.GetString("default_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $(document).ready(function () {
        ///    $(&apos;#tabstrip&apos;).kendoTabStrip({
        ///        animation: {
        ///            open:
        ///            {
        ///                effects: &apos;fadeIn&apos;
        ///            }
        ///        }
        ///    });
        ///
        ///    $(&quot;.makeAGrid&quot;).each(function() {
        ///        $(this).kendoGrid({
        ///            height: 550,
        ///            sortable: true
        ///        });
        ///    });
        ///});.
        /// </summary>
        internal static string sysinfojs {
            get {
                return ResourceManager.GetString("sysinfojs", resourceCulture);
            }
        }
    }
}
